# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ffb7fb014690b20a4ecce0bef3970aa960ef34bac3bf02840fdf3c2f23cb5bd3ad56f3d3060ff0088df7cd4510fa0e921b0d920fbf19f1f17ceff21205915a16

test:
  secret_key_base: 201d89b44334ec4fcac0e1f8816d6da82980a5aaf14e1f8615af9c66e98711524011ff023c6993534c173656dbbe85bfdd0f9161446536e14b831115c5a0464f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
